CREATE SCHEMA IF NOT EXISTS schema_clients;

CREATE TABLE IF NOT EXISTS schema_clients.demo_customer (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  nif VARCHAR(250) NOT NULL,
  docNum VARCHAR(250) NOT NULL,
  email VARCHAR(250) DEFAULT NULL,
  givenName VARCHAR(250) DEFAULT NULL
);

